# Generated by Django 2.1.7 on 2019-03-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='code',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='Шифр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competence',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competence',
            name='type',
            field=models.CharField(default=1, max_length=50, verbose_name='Расшифровка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(max_length=400, unique=True, verbose_name='Название'),
        ),
    ]
